routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
| Middleware options can be located in `app/Http/Kernel.php`
|
*/

// Authentication Routes
Auth::routes();

// Public Routes
Route::group(['middleware' => 'web'], function () {

    // Activation Routes
    Route::get('/activate', ['as' => 'activate', 'uses' => 'Auth\ActivateController@initial']);

    Route::get('/activate/{token}', ['as' => 'authenticated.activate', 'uses' => 'Auth\ActivateController@activate']);
    Route::get('/activation', ['as' => 'authenticated.activation-resend', 'uses' => 'Auth\ActivateController@resend']);
    Route::get('/exceeded', ['as' => 'exceeded', 'uses' => 'Auth\ActivateController@exceeded']);

    // Socialite Register Routes
    Route::get('/social/redirect/{provider}', ['as' => 'social.redirect', 'uses' => 'Auth\SocialController@getSocialRedirect']);
    Route::get('/social/handle/{provider}', ['as' => 'social.handle', 'uses' => 'Auth\SocialController@getSocialHandle']);

    // Route to for user to reactivate their user deleted account.
    Route::get('/re-activate/{token}', ['as' => 'user.reactivate', 'uses' => 'RestoreUserController@userReActivate']);

    Route::resource('/register_member', 'RegisterMemberController');
});

// Registered and Activated User Routes
Route::group(['middleware' => ['auth']], function () {

    // Activation Routes
    Route::get('/activation-required', ['uses' => 'Auth\ActivateController@activationRequired'])->name('activation-required');
    Route::get('/logout', ['uses' => 'Auth\LoginController@logout'])->name('logout');

    //  Homepage Route - Redirect based on user role is in controller.
    Route::get('/home', ['as' => 'public.home',   'uses' => 'UserController@index']);

    // Show users profile - viewable by other users.
    Route::get('profile/{username}', [
        'as'        => '{username}',
        'uses'      => 'ProfilesController@show',
    ]);
});

// Registered, activated, and is current user routes.
Route::group(['middleware'=> ['auth']], function () {

    // Homepage Route
    Route::get('/', 'DashboardController@index')->name('welcome');

    // User Profile and Account Routes
    Route::resource(
        'profile',
        'ProfilesController', [
            'only'  => [
                'show',
                'edit',
                'update',
                'create',
            ],
        ]
    );
    Route::put('profile/{username}/updateUserAccount', [
        'as'        => '{username}',
        'uses'      => 'ProfilesController@updateUserAccount',
    ]);
    Route::put('profile/{username}/updateUserPassword', [
        'as'        => '{username}',
        'uses'      => 'ProfilesController@updateUserPassword',
    ]);
    Route::delete('profile/{username}/deleteUserAccount', [
        'as'        => '{username}',
        'uses'      => 'ProfilesController@deleteUserAccount',
    ]);

    // Route to show user avatar
    Route::get('images/profile/{id}/avatar/{image}', [
        'uses'      => 'ProfilesController@userProfileAvatar',
    ]);

    // Route to upload user avatar.
    Route::post('avatar/upload', ['as' => 'avatar.upload', 'uses' => 'ProfilesController@upload']);

    Route::resource('/dashboard', 'DashboardController');

    Route::get('/institute/data', 'InstituteController@getData');
    Route::resource('/institute', 'InstituteController');
    Route::resource('/institute-program', 'InstituteProgramController');
    Route::resource('/faculty', 'FacultyController');
    Route::resource('/program', 'ProgramController');
    Route::resource('/news', 'NewsController');

});

app/Models/Institute.php
<?php

namespace App\Models;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Institute extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'code',
        'type',
        'name',
        'address',
        'city',
        'postcode',
        'state_id',
        'lat',
        'lng',
        'email',
        'phone',
        'faks',
        'website'
    ];

    protected $dates = [
        'created_at',
        'deleted_at'
    ];

    public function institutePrograms()
    {
        return $this->hasMany('App\Models\InstituteProgram');
    }

    public function news()
    {
        return $this->hasMany('App\Models\News');
    }

    public function getTypeNameAttribute()
    {
        if($this->attributes['type'] == 1){
          return 'IPTA';
        }else if($this->attributes['type'] == 2){
          return 'IPTS';
        }else if($this->attributes['type'] == 3){
          return 'Kolej Komuniti';
        }else if($this->attributes['type'] == 4){
          return 'Poli';
        }

        return '';
    }
}

app/Http/Controllers/InstituteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Institute;
use App\Models\News;
use App\Models\InstituteProgram;
use App\Models\Faculty;
use App\Models\Program;
use Illuminate\Support\Facades\DB;

class InstituteController extends Controller
{

    public $states = [
      '1' => 'Johor',
      '2' => 'Kedah',
      '3' => 'Kelantan',
      '4' => 'Terengganu',
      '5' => 'Melaka',
      '6' => 'Negeri Sembilan',
      '7' => 'Pahang',
      '8' => 'Perak',
      '9' => 'Perlis',
      '10' => 'Pulau Pinang',
      '11' => 'Sabah',
      '12' => 'Sarawak',
      '13' => 'Selangor',
      '14' => 'W.P. Kuala Lumpur',
      '15' => 'W.P. Labuan',
      '16' => 'W.P. Putrajaya',
    ];


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $institute = Institute::all();

        $data = [
          'institute' => $institute
        ];

        return view('institute.index')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
          'form_action' => route('institute.store'),
          'states' => $this->states
        ];

        return view('institute.form')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Institute::create( $request->except('_token') );

        \Session::flash('alert-success', 'Institut berjaya ditambah.');
        return redirect()->route('institute.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $institute = Institute::find($id);

        $data = [
          'institute' => $institute,
          'news' => News::where('institute_id', $id)->get(),
          'instituteProgram' => InstituteProgram::with(['faculty', 'program'])->where('institute_id', $id)->get(),
          'faculty' => Faculty::all(),
          'program' => Program::all(),
        ];

        return view('institute.show')->with($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [
          'form_action' => route('institute.update', $id),
          'method' => 'PUT',
          'states' => $this->states,
          'institute' => Institute::find($id)
        ];

        return view('institute.form')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Institute::find($id)->update( $request->except('_token') );

        \Session::flash('alert-success', 'Institut berjaya dikemas kini.');
        return redirect()->route('institute.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         Institute::find($id)->delete();
    }

    public function getJson(Request $request)
    {
        $search = $request->get('search');
        $type = $request->get('type');
        $state = $request->get('state_name');
        $program = $request->get('program_code');
        $faculty = $request->get('faculty_code');
        $level = $request->get('level');

        $institute = new Institute;

        if(!empty($search)){
          $institute = $institute->where(function($query) use($search)
          {
              $query->where('name', 'LIKE', '%' . $search . '%')
              ->orWhere('city', 'LIKE', '%' . $search . '%')
              ->orWhere('state_name', 'LIKE', '%' . $search . '%');
          });
        }

        if(!empty($type)){
            $institute = $institute->where('type', $type);
        }

        if(!empty($state)){
          $state = strtolower($state);
          if($state != 'all'){
            $institute = $institute->where('state_name', $state);
          }
        }

        if(!empty($program)){
          $institute = $institute->whereHas('institutePrograms', function($query) use($program){
            $query->where('program_code', $program);
          });
        }

        if(!empty($faculty)){
          $institute = $institute->whereHas('institutePrograms', function($query) use($faculty){
            $query->where('faculty_code', $faculty);
          });
        }

        if(!empty($level)){
          $institute = $institute->whereHas('institutePrograms', function($query) use($level){
            $query->where('level', $level);
          });
        }

        $institute = $institute->get();

        return $institute->toJson();
    }

    public function getJsonOne($id)
    {
        $institute = Institute::where('id', $id)->with(['news', 'institutePrograms', 'institutePrograms.program', 'institutePrograms.faculty'])->first();

        $institute->news = $institute->news->map(function($item, $key){
            $item->date = $item->created_at->diffForHumans();
            return $item;
        });

        $institute->institutePrograms = $institute->institutePrograms->map(function($item, $key){
            $item->duration = $item->durationReal;
            return $item;
        });

        return $institute->toJson();
    }

    public function getStates()
    {
        $institute = Institute::groupBy('state_name')->select('state_name', DB::raw('count(*) as total'))->get();

        return $institute->toJson();
    }

    public function getCategories()
    {
        $institute = Institute::groupBy('type')->select('type', DB::raw('count(*) as total'))->get();

        return $institute->toJson();
    }

    public function getRankings($type)
    {
        if($type == 'world'){
          $institute = Institute::where('ranking_world_no', '!=', 'NULL')->orderBy('ranking_world_no', 'asc')->get();
        }else{
          $institute = Institute::where('ranking_asia_no', '!=', 'NULL')->orderBy('ranking_asia_no', 'asc')->get();
        }

        $institute = $institute->map(function($item, $key){
            if (strpos($item->name, '-') !== false) {
                $item->name = substr($item->name, 0, strrpos( $item->name, '-'));;
            }
            return $item;
        });
        //
        // $institute = $institute->sortBy("ranking_world_no")->unique('group')->values()->all();
        //
        //
        if($type == 'world'){
          $institute = $institute->unique('group')->values()->all();
        }else{
          $institute = $institute->unique('group')->values()->all();
        }

        return json_encode($institute);
    }
}

resources/views/institute/form.blade.php
@extends('layouts.app')

@section('template_title')
  Institut Baru
@endsection

@section('content')

<div class="m-portlet m-portlet--tab">
			<div class="m-portlet__head">
				<div class="m-portlet__head-caption">
					<div class="m-portlet__head-title">
						<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
						</span>
						<h3 class="m-portlet__head-text">
              @if(isset($method))
              Kemas Kini Institut
              @else
              Institut Baru
              @endif
						</h3>
					</div>
				</div>
			</div>
			<!--begin::Form-->
			<form class="m-form m-form--fit m-form--label-align-right" action="{{ $form_action }}" method="post" >

        @if(isset($method))
        {{ method_field($method) }}
        @endif
        {{ csrf_field() }}

				<div class="m-portlet__body">
          <div class="form-group m-form__group row">
						<label class="col-lg-2 col-form-label">Jenis</label>
            <div class="col-lg-6">
              <select name="type" class="form-control m-input m-input--solid" value="{{ $institute->type or old('type') }}">
                <option value="1">IPTA</option>
                <option value="2">IPTS</option>
                <option value="3">Kolej Komuniti</option>
                <option value="4">Politeknik</option>
  						</select>
            </div>
					</div>
					<div class="form-group m-form__group row">
						<label class="col-lg-2 col-form-label">Kod *</label>
            <div class="col-lg-6">
						  <input name="code" type="text" class="form-control m-input m-input--solid" placeholder="Kod institut" value="{{ $institute->code or old('code') }}" required>
            </div>
					</div>
          <div class="form-group m-form__group row">
						<label class="col-lg-2 col-form-label">Nama *</label>
            <div class="col-lg-6">
			        <input name="name" type="text" class="form-control m-input m-input--solid" placeholder="Nama institut" value="{{ $institute->name or old('name') }}" required>
            </div>
					</div>
          <div class="form-group m-form__group row">
						<label class="col-lg-2 col-form-label">Emel</label>
            <div class="col-lg-6">
			        <input name="email" type="email" class="form-control m-input m-input--solid" placeholder="Emel institut" value="{{ $institute->email or old('email') }}">
            </div>
					</div>
          <div class="form-group m-form__group row">
						<label class="col-lg-2 col-form-label">Telefon</label>
            <div class="col-lg-6">
			        <input name="phone" type="text" class="form-control m-input m-input--solid" placeholder="No. Telefon institut" value="{{ $institute->phone or old('phone') }}">
            </div>
					</div>
          <div class="form-group m-form__group row">
						<label class="col-lg-2 col-form-label">Faks</label>
            <div class="col-lg-6">
			        <input name="faks" type="text" class="form-control m-input m-input--solid" placeholder="No. Faks institut" value="{{ $institute->faks or old('faks') }}">
            </div>
					</div>
          <div class="form-group m-form__group row">
						<label class="col-lg-2 col-form-label">Laman sesawang</label>
            <div class="col-lg-6">
			        <input name="website" type="text" class="form-control m-input m-input--solid" placeholder="Laman sesawang institut" value="{{ $institute->website or old('website') }}">
            </div>
					</div>
          <div class="form-group m-form__group row">
            <label class="col-lg-2 col-form-label">Latitud dan longitud *</label>
            <div class="col-lg-6">
              <div class="input-group">
                <input name="lat" type="number" step="0.000001" class="form-control m-input m-input--solid" placeholder="Latitud" required value="{{ $institute->lat or old('lat') }}">
                <input name="lng" type="number" step="0.000001" class="form-control m-input m-input--solid" placeholder="Longitud" required value="{{ $institute->lng or old('lng') }}">
              </div>
            </div>
          </div>
          <div class="form-group m-form__group row">
						<label class="col-lg-2 col-form-label">Alamat</label>
            <div class="col-lg-6">
              <textarea name="address" class="form-control m-input m-input--solid" rows="3" placeholder="Alamat penuh institut" value="{{ $institute->address or old('address') }}"></textarea>
            </div>
					</div>
          <div class="form-group m-form__group row">
						<label class="col-lg-2 col-form-label">Poskod</label>
            <div class="col-lg-6">
              <input name="postcode" type="number" class="form-control m-input m-input--solid" placeholder="Poskod institut" value="{{ $institute->postcode or old('postcode') }}">
            </div>
					</div>
          <div class="form-group m-form__group row">
						<label class="col-lg-2 col-form-label">Bandar</label>
            <div class="col-lg-6">
              <input name="city" type="text" class="form-control m-input m-input--solid" placeholder="Bandar Institut" value="{{ $institute->city or old('city') }}">
            </div>
					</div>
          <div class="form-group m-form__group row">
						<label class="col-lg-2 col-form-label">Negeri</label>
            <div class="col-lg-6">
              <select name="state_id" class="form-control m-input m-input--solid" value="{{ $institute->state_id or old('state_id') }}">
                @foreach($states as $key => $state)
  							<option value="{{ $key }}">{{ $state }}</option>
                @endforeach
  						</select>
            </div>
					</div>


				</div>
				<div class="m-portlet__foot m-portlet__foot--fit">
					<div class="m-form__actions">
						<button type="submit" class="btn btn-success">Submit</button>
						<a class="btn btn-secondary" href="{{ route('institute.index') }}">Cancel</a>
					</div>
				</div>
			</form>
			<!--end::Form-->
		</div>

@endsection

@push('js')
<script>

  $('[name="type"]').val('{{ $institute->type or null }}');
  $('[name="state_id"]').val('{{ $institute->state_id or null }}');

</script>
@endpush

resources/views/institute/index.blade.php
@extends('layouts.app')

@section('template_title')
  Institute
@endsection

@section('content')

@component('partials.portlet')
    @slot('title')
        Senarai Institut
    @endslot

    @slot('content')
    <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
      <div class="row align-items-center">
        <div class="col-xl-8 order-2 order-xl-1">
          <div class="form-group m-form__group row align-items-center">
            <div class="col-md-4">
              <div class="m-input-icon m-input-icon--left">
                <input type="text" class="form-control m-input" placeholder="Search..." id="generalSearch">
                <span class="m-input-icon__icon m-input-icon__icon--left">
                  <span>
                    <i class="la la-search"></i>
                  </span>
                </span>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-4 order-1 order-xl-2 m--align-right">
          <a href="{{ route('institute.create') }}" class="btn btn-info m-btn m-btn--custom m-btn--icon m-btn--air">
            <span>
              <i class="la la-plus"></i>
              <span>
                Tambah IPT
              </span>
            </span>
          </a>
          <div class="m-separator m-separator--dashed d-xl-none"></div>
        </div>
      </div>
    </div>

    <table class="m-datatable" id="html_table" width="100%">
      <thead>
        <tr>
          <th>Type</th>
          <th>Name</th>
          <th>Lokasi</th>
          <th>Poskod</th>
          <th>Bandar</th>
          <th>Negeri</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="institute_table">
        @foreach($institute as $inst)
        <tr>
          <td>{{ $inst->typeName }}</td>
          <td>
            <a href="{{ route('institute.show', $inst->id) }}">{{ $inst->name }}</a>
          </td>
          <td>{{ $inst->lat }} - {{ $inst->lng }}</td>
          <td>{{ $inst->postcode }}</td>
          <td>{{ $inst->city }}</td>
          <td>{{ $inst->state }}</td>
          <td>
            <a href="{{ route('institute.edit', $inst->id) }}" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="kemas kini">
              <i class="la la-edit"></i>
            </a>
            <button href="{{ route('institute.destroy', $inst->id) }}" class="m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill delete-sa2" title="Padam">
              <i class="la la-trash"></i>
            </button>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
    @endslot

@endcomponent



@endsection

@push('js')
<script src="{{ asset('js/institute.js') }}" type="text/javascript"></script>
<script>
$( document ).ready(function(){
  $(".m-bootstrap-select").selectpicker();

  $('#html_table').on('click', '.delete-sa2',function(e) {

      console.log('enter delete');
      var url = $(this).attr('href');

      swal({
          title: 'Anda Pasti?',
          text: "Institut akan padam!",
          type: 'warning',
          showCancelButton: true,
          confirmButtonText: 'Ya!',
          preConfirm: function(email) {
              return new Promise(function(resolve, reject) {
                  $.ajax({
                      type: "DELETE",
                      url: url,
                      headers: {
                          'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                      },
                      success: function(msg) {
                          resolve()
                      },
                      error: function(req, status, err) {
                          toast('error', 'Something when wrong');
                      }
                  });
              })
          },
      }).then(function(result) {
          if (result.value) {
              swal(
                  'Dipadam!',
                  'Insitut telah dipadam.',
                  'success'
              ).then(function(){
                location.reload();
              })
          }
      });
  });

});
</script>
@endpush

resources/views/institute/show.blade.php
@extends('layouts.app')

@section('template_title')
  Maklumat Institut
@endsection

@section('content')
<div class="m-portlet m-portlet--creative m-portlet--first m-portlet--bordered-semi">
	<div class="m-portlet__head">
		<div class="m-portlet__head-caption">
			<div class="m-portlet__head-title">
				<span class="m-portlet__head-icon m--hide">
					<i class="flaticon-statistics"></i>
				</span>
				<h3 class="m-portlet__head-text">
					Maklumat
				</h3>
				<h2 class="m-portlet__head-label m-portlet__head-label--danger">
					<span>{{ $institute->name }}</span>
				</h2>
			</div>
		</div>
		<div class="m-portlet__head-tools">
			<ul class="m-portlet__nav">
				<li class="m-portlet__nav-item">
					<a href="{{ route('institute.edit', $institute->id) }}" class="m-portlet__nav-link m-portlet__nav-link--icon"><i class="la la-cog"></i></a>
				</li>
			</ul>
		</div>
	</div>
  <div class="m-portlet__body">
    <div class="table-responsive">
		    <table class="table">
				<tbody>
					<tr>
					 	<th width="200">Kod</th>
					 	<td>{{ $institute->code }}</td>
					</tr>
					<tr>
					 	<th>Nama</th>
					 	<td>{{ $institute->name }}</td>
					</tr>
					<tr>
					 	<th>Emel</th>
					 	<td>{{ $institute->email }}</td>
					</tr>
					<tr>
					 	<th>No. Telefon</th>
					 	<td>{{ $institute->phone }}</td>
					</tr>
					<tr>
					 	<th>Faks</th>
					 	<td>{{ $institute->faks }}</td>
					</tr>
					<tr>
					 	<th>Laman Sesawang</th>
					 	<td>{{ $institute->website }}</td>
					</tr>
					<tr>
					 	<th>Latitud dan Longitud</th>
					 	<td>{{ $institute->lat }} - {{ $institute->lng }}</td>
					</tr>
					<tr>
					 	<th>Alamat</th>
					 	<td>{{ $institute->address }}</td>
					</tr>
					<tr>
					 	<th>Poskod</th>
					 	<td>{{ $institute->postcode }}</td>
					</tr>
					<tr>
					 	<th>Bandar</th>
					 	<td>{{ $institute->city }}</td>
					</tr>
					<tr>
					 	<th>Negeri</th>
					 	<td>{{ $institute->state }}</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

<!--begin::Portlet-->
<div class="m-portlet m-portlet--tabs">
    <div class="m-portlet__head">
        <div class="m-portlet__head-tools">
            <ul class="nav nav-tabs m-tabs-line m-tabs-line--success m-tabs-line--2x" role="tablist">
                <li class="nav-item m-tabs__item">
                    <a class="nav-link m-tabs__link active" data-toggle="tab" href="#tab_program" role="tab">
                        <i class="fa fa-graduation-cap"></i> Program
                    </a>
                </li>
                <li class="nav-item m-tabs__item">
                    <a class="nav-link m-tabs__link" data-toggle="tab" href="#tab_news" role="tab">
                        <i class="fa fa-newspaper-o"></i> Info dan Aktiviti
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="m-portlet__body">
        <div class="tab-content">
            <div class="tab-pane active" id="tab_program" role="tabpanel">

              <h5 class="mb-4">Tambah Program Baru</h5>
              <form class="m-form m-form--fit m-form--label-align-right" action="{{ route('institute-program.store') }}" method="post">
                {{ csrf_field() }}

                <input name="institute_id" type="hidden" value="{{ $institute->id }}" />
                <div class="form-group m-form__group row">
      						<label class="col-lg-2 col-form-label">Fakulti</label>
                  <div class="col-lg-6">
                    <select name="faculty_code" class="form-control m-input m-input--solid mr-4">
                      @foreach($faculty as $fac)
                      <option value="{{ $fac->code }}">{{ $fac->name }}</option>
                      @endforeach
        						</select>
                  </div>
      					</div>
                <div class="form-group m-form__group row">
      						<label class="col-lg-2 col-form-label">Program</label>
                  <div class="col-lg-6">
                    <select name="program_code" class="form-control m-input m-input--solid mr-4" >
                      @foreach($program as $prog)
                      <option value="{{ $prog->code }}">{{ $prog->name }}</option>
                      @endforeach
        						</select>
                  </div>
      					</div>
                <div class="form-group m-form__group row">
      						<label class="col-lg-2 col-form-label">Level</label>
                  <div class="col-lg-6">
                    <select name="level" class="form-control m-input m-input--solid mr-4">
                      <option value="b">Bachelor</option>
                      <option value="d">Diploma</option>
                      <option value="m">Master</option>
                      <option value="p">PHD</option>
                      <option value="f">Foundation</option>
                      <option value="s">Sijil</option>
        						</select>
                  </div>
      					</div>
                <div class="form-group m-form__group row">
      						<label class="col-lg-2 col-form-label">Major</label>
                  <div class="col-lg-6">
                    <input name="major" type="text" class="form-control m-input m-input--solid" placeholder="Major">
                  </div>
      					</div>

                <div class="m-portlet__foot m-portlet__foot--fit">
        					<div class="m-form__actions">
        						<button type="submit" class="btn btn-success">Tambah</button>
        					</div>
        				</div>
              </form>

              <table width="100%" class="table mt-4">
                <thead>
                  <tr>
                    <th>Fakulti</th>
                    <th>Program</th>
                    <th>Level</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($instituteProgram as $program)
                  <tr>
                    <td>{{ $program->faculty->name }}</td>
                    <td>{{ $program->program->name }}</td>
                    <td>{{ $program->levelName }}</td>
                  </tr>
                  @endforeach
                </tbody>
              </table>

            </div>
            <div class="tab-pane" id="tab_news" role="tabpanel">

              <table width="100%" class="table">
                <thead>
                  <tr>
                    <th>Tajuk</th>
                    <th>Kandungan</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($news as $new)
                  <tr>
                    <td>
                      {{ $new->data['title'] }}
                    </td>
                    <td>
                      {{ $new->data['content'] }}
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>

            </div>
        </div>
    </div>
</div>
<!--end::Portlet-->

@endsection

@push('js')
<script>

  $('[name="level"]').val('');
  $('[name="program_code"]').val('');
  $('[name="faculty_code"]').val('');

</script>
@endpush