routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
| Middleware options can be located in `app/Http/Kernel.php`
|
*/

// Authentication Routes
Auth::routes();

// Public Routes
Route::group(['middleware' => 'web'], function () {

    // Activation Routes
    Route::get('/activate', ['as' => 'activate', 'uses' => 'Auth\ActivateController@initial']);

    Route::get('/activate/{token}', ['as' => 'authenticated.activate', 'uses' => 'Auth\ActivateController@activate']);
    Route::get('/activation', ['as' => 'authenticated.activation-resend', 'uses' => 'Auth\ActivateController@resend']);
    Route::get('/exceeded', ['as' => 'exceeded', 'uses' => 'Auth\ActivateController@exceeded']);

    // Socialite Register Routes
    Route::get('/social/redirect/{provider}', ['as' => 'social.redirect', 'uses' => 'Auth\SocialController@getSocialRedirect']);
    Route::get('/social/handle/{provider}', ['as' => 'social.handle', 'uses' => 'Auth\SocialController@getSocialHandle']);

    // Route to for user to reactivate their user deleted account.
    Route::get('/re-activate/{token}', ['as' => 'user.reactivate', 'uses' => 'RestoreUserController@userReActivate']);

    Route::resource('/register_member', 'RegisterMemberController');
});

// Registered and Activated User Routes
Route::group(['middleware' => ['auth']], function () {

    // Activation Routes
    Route::get('/activation-required', ['uses' => 'Auth\ActivateController@activationRequired'])->name('activation-required');
    Route::get('/logout', ['uses' => 'Auth\LoginController@logout'])->name('logout');

    //  Homepage Route - Redirect based on user role is in controller.
    Route::get('/home', ['as' => 'public.home',   'uses' => 'UserController@index']);

    // Show users profile - viewable by other users.
    Route::get('profile/{username}', [
        'as'        => '{username}',
        'uses'      => 'ProfilesController@show',
    ]);
});

// Registered, activated, and is current user routes.
Route::group(['middleware'=> ['auth']], function () {

    // Homepage Route
    Route::get('/', 'DashboardController@index')->name('welcome');

    // User Profile and Account Routes
    Route::resource(
        'profile',
        'ProfilesController', [
            'only'  => [
                'show',
                'edit',
                'update',
                'create',
            ],
        ]
    );
    Route::put('profile/{username}/updateUserAccount', [
        'as'        => '{username}',
        'uses'      => 'ProfilesController@updateUserAccount',
    ]);
    Route::put('profile/{username}/updateUserPassword', [
        'as'        => '{username}',
        'uses'      => 'ProfilesController@updateUserPassword',
    ]);
    Route::delete('profile/{username}/deleteUserAccount', [
        'as'        => '{username}',
        'uses'      => 'ProfilesController@deleteUserAccount',
    ]);

    // Route to show user avatar
    Route::get('images/profile/{id}/avatar/{image}', [
        'uses'      => 'ProfilesController@userProfileAvatar',
    ]);

    // Route to upload user avatar.
    Route::post('avatar/upload', ['as' => 'avatar.upload', 'uses' => 'ProfilesController@upload']);

    Route::resource('/dashboard', 'DashboardController');

    Route::get('/institute/data', 'InstituteController@getData');
    Route::resource('/institute', 'InstituteController');
    Route::resource('/institute-program', 'InstituteProgramController');
    Route::resource('/faculty', 'FacultyController');
    Route::resource('/program', 'ProgramController');
    Route::resource('/news', 'NewsController');

});

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class News extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'institute_id',
        'data',
    ];

    protected $dates = [
        'deleted_at',
        'created_at'
    ];

    protected $casts = [
        'data' => 'json',
    ];

    public function institute()
    {
        return $this->belongsTo('App\Models\Institute');
    }

}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\News;
use App\Models\Institute;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $news = News::all();

        $data = [
          'news' => $news
        ];

        return view('news.index')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
          'form_action' => route('news.store'),
          'institute' => Institute::all()
        ];

        return view('news.form')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $news = new News();
        $data = $news->data;
        $data['title'] = $request->title;
        $data['content'] = $request->content;
        $news->data = $data;
        $news->institute_id = $request->institute_id;

        $news->save();

        \Session::flash('alert-success', 'Info berjaya ditambah.');
        return redirect()->route('news.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $news = News::find($id);

        $data = [
          'news' => $news,
        ];

        return view('news.show')->with($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [
          'form_action' => route('news.update', $id),
          'institute' => Institute::all(),
          'method' => 'PUT',
          'news' => News::find($id)
        ];

        return view('news.form')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $news = News::find($id);
        $data = $news->data;
        $data['title'] = $request->title;
        $data['content'] = $request->content;
        $news->data = $data;
        $news->institute_id = $request->institute_id;

        $news->save();

        \Session::flash('alert-success', 'Info berjaya dikemas kini.');
        return redirect()->route('news.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        News::find($id)->delete();
    }

    public function getJson(Request $request)
    {
        $news = new News;

        $news = $news->with(['institute'])->get()->map(function($item, $key){
            $item->date = $item->created_at->diffForHumans();
            return $item;
        });

        return json_encode($news);
    }

    public function getJsonOne($id)
    {
        $news = News::where('id', $id)->first();

        $news->date = $news->created_at->diffForHumans();

        return $news->toJson();
    }
}

resources/views/news/form.blade.php
@extends('layouts.app')

@section('template_title')
  Info dan Aktiviti Baru
@endsection

@section('content')

<div class="m-portlet m-portlet--tab">
			<div class="m-portlet__head">
				<div class="m-portlet__head-caption">
					<div class="m-portlet__head-title">
						<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
						</span>
						<h3 class="m-portlet__head-text">
              @if(isset($method))
              Kemas Kini
              @else
              Butiran
              @endif
						</h3>
					</div>
				</div>
			</div>
			<!--begin::Form-->
			<form class="m-form m-form--fit m-form--label-align-right" action="{{ $form_action }}" method="post" >

        @if(isset($method))
        {{ method_field($method) }}
        @endif
        {{ csrf_field() }}

				<div class="m-portlet__body">
          <div class="form-group m-form__group row">
						<label class="col-lg-2 col-form-label">Institut</label>
            <div class="col-lg-6">
              <select name="institute_id" class="form-control m-input m-input--solid" value="{{ $news->institute_id or old('institute_id') }}">
                @foreach($institute as $inst)
                <option value="{{ $inst->id }}">{{ $inst->name }}</option>
                @endforeach
  						</select>
            </div>
					</div>
          <div class="form-group m-form__group row">
						<label class="col-lg-2 col-form-label">Title</label>
            <div class="col-lg-6">
			        <input name="title" type="text" class="form-control m-input m-input--solid" placeholder="Tajuk info atau aktiviti" value="{{ $news->data['title'] or old('title') }}" required>
            </div>
					</div>
          <div class="form-group m-form__group row">
						<label class="col-lg-2 col-form-label">Deskripsi</label>
            <div class="col-lg-6">
              <textarea name="content" class="form-control m-input m-input--solid" rows="3" placeholder="Deskripsi info atau aktiviti" value="{{ $news->data['content'] or old('content') }}"></textarea>
            </div>
					</div>
				</div>
				<div class="m-portlet__foot m-portlet__foot--fit">
					<div class="m-form__actions">
						<button type="submit" class="btn btn-success">Submit</button>
						<a class="btn btn-secondary" href="{{ route('news.index') }}">Cancel</a>
					</div>
				</div>
			</form>
			<!--end::Form-->
		</div>

@endsection

@push('js')
<script>

  $('[name="institute_id"]').val('{{ $news->institute_id or null }}');

</script>
@endpush

resources/views/news/index.blade.php
@extends('layouts.app')

@section('template_title')
  Info dan Aktiviti
@endsection

@section('content')

@component('partials.portlet')
    @slot('title')
        Senarai Info dan Aktiviti
    @endslot

    @slot('content')
    <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
      <div class="row align-items-center">
        <div class="col-xl-8 order-2 order-xl-1">
          <div class="form-group m-form__group row align-items-center">
            <div class="col-md-4">
              <div class="m-input-icon m-input-icon--left">
                <input type="text" class="form-control m-input" placeholder="Search..." id="generalSearch">
                <span class="m-input-icon__icon m-input-icon__icon--left">
                  <span>
                    <i class="la la-search"></i>
                  </span>
                </span>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-4 order-1 order-xl-2 m--align-right">
          <a href="{{ route('news.create') }}" class="btn btn-info m-btn m-btn--custom m-btn--icon m-btn--air">
            <span>
              <i class="la la-plus"></i>
              <span>
                Tambah Info dan Aktiviti
              </span>
            </span>
          </a>
          <div class="m-separator m-separator--dashed d-xl-none"></div>
        </div>
      </div>
    </div>

    <table class="m-datatable" id="html_table" width="100%">
      <thead>
        <tr>
          <th>Institut</th>
          <th>Tajuk</th>
          <th>Kandungan</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        @foreach($news as $new)
        <tr>
          <td>
            {{ $new->institute->name }}
          </td>
            <td>
              {{ $new->data['title'] }}
            </td>
              <td>
                {{ $new->data['content'] }}
              </td>
          <td>
            <a href="{{ route('news.edit', $new->id) }}" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="kemas kini">
              <i class="la la-edit"></i>
            </a>
            <button href="{{ route('news.destroy', $new->id) }}" class="m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill delete-sa2" title="Padam">
              <i class="la la-trash"></i>
            </button>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
    @endslot

@endcomponent



@endsection

@push('js')
<script>

var DatatableHtmlTableDemo = function() {
  //== Private functions

  // demo initializer
  var demo = function() {

    var datatable = $('.m-datatable').mDatatable({
      data: {
        saveState: {cookie: false},
      },
      search: {
        input: $('#generalSearch'),
      }
    });
  };

  return {
    //== Public functions
    init: function() {
      // init dmeo
      demo();
    },
  };
}();

jQuery(document).ready(function() {
  DatatableHtmlTableDemo.init();
});


jQuery(document).ready(function(){
  $(".m-bootstrap-select").selectpicker();

  $('.delete-sa2').click(function(e) {

      var url = $(this).attr('href');

      swal({
          title: 'Anda Pasti?',
          text: "Info akan padam!",
          type: 'warning',
          showCancelButton: true,
          confirmButtonText: 'Ya!',
          preConfirm: function(email) {
              return new Promise(function(resolve, reject) {
                  $.ajax({
                      type: "DELETE",
                      url: url,
                      headers: {
                          'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                      },
                      success: function(msg) {
                          resolve()
                      },
                      error: function(req, status, err) {
                          toast('error', 'Something when wrong');
                      }
                  });
              })
          },
      }).then(function(result) {
          if (result.value) {
              swal(
                  'Dipadam!',
                  'Info telah dipadam.',
                  'success'
              ).then(function(){
                location.reload();
              })
          }
      });
  });

});
</script>
@endpush

resources/views/news/show.blade.php
@extends('layouts.app')

@section('template_title')
  Maklumat Institut
@endsection

@section('content')
<div class="m-portlet m-portlet--creative m-portlet--first m-portlet--bordered-semi">
	<div class="m-portlet__head">
		<div class="m-portlet__head-caption">
			<div class="m-portlet__head-title">
				<span class="m-portlet__head-icon m--hide">
					<i class="flaticon-statistics"></i>
				</span>
				<h3 class="m-portlet__head-text">
					Maklumat
				</h3>
				<h2 class="m-portlet__head-label m-portlet__head-label--danger">
					<span>{{ $institute->name }}</span>
				</h2>
			</div>
		</div>
		<div class="m-portlet__head-tools">
			<ul class="m-portlet__nav">
				<li class="m-portlet__nav-item">
					<a href="{{ route('institute.edit', $institute->id) }}" class="m-portlet__nav-link m-portlet__nav-link--icon"><i class="la la-cog"></i></a>
				</li>
			</ul>
		</div>
	</div>
  <div class="m-portlet__body">
    <div class="table-responsive">
		    <table class="table">
				<tbody>
					<tr>
					 	<th width="200">Kod</th>
					 	<td>{{ $institute->code }}</td>
					</tr>
					<tr>
					 	<th>Nama</th>
					 	<td>{{ $institute->name }}</td>
					</tr>
					<tr>
					 	<th>Emel</th>
					 	<td>{{ $institute->email }}</td>
					</tr>
					<tr>
					 	<th>No. Telefon</th>
					 	<td>{{ $institute->phone }}</td>
					</tr>
					<tr>
					 	<th>Faks</th>
					 	<td>{{ $institute->faks }}</td>
					</tr>
					<tr>
					 	<th>Laman Sesawang</th>
					 	<td>{{ $institute->website }}</td>
					</tr>
					<tr>
					 	<th>Latitud dan Longitud</th>
					 	<td>{{ $institute->lat }} - {{ $institute->lng }}</td>
					</tr>
					<tr>
					 	<th>Alamat</th>
					 	<td>{{ $institute->address }}</td>
					</tr>
					<tr>
					 	<th>Poskod</th>
					 	<td>{{ $institute->postcode }}</td>
					</tr>
					<tr>
					 	<th>Bandar</th>
					 	<td>{{ $institute->city }}</td>
					</tr>
					<tr>
					 	<th>Negeri</th>
					 	<td>{{ $institute->state }}</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
@endsection